apiVersion: v2
type: application
name: quote
version: 0.1.1
appVersion: "2.2.0"
description: OTel Demo Quote Service - PHP shipping quote
home: https://github.com/open-telemetry/opentelemetry-demo
sources:
  - https://github.com/open-telemetry/opentelemetry-demo
keywords:
  - opentelemetry
  - demo
  - quote
