apiVersion: v2
type: application
name: flagd
version: 0.1.0
appVersion: "0.12.9"
description: OTel Demo Flagd - OpenFeature-compatible feature flag service
home: https://github.com/open-telemetry/opentelemetry-demo
sources:
  - https://github.com/open-feature/flagd
keywords:
  - opentelemetry
  - demo
  - flagd
  - feature-flags
  - openfeature
