apiVersion: v2
type: application
name: image-provider
version: 0.1.0
appVersion: "2.2.0"
description: OTel Demo Image Provider - serves product images
home: https://github.com/open-telemetry/opentelemetry-demo
sources:
  - https://github.com/open-telemetry/opentelemetry-demo
keywords:
  - opentelemetry
  - demo
  - image-provider
