apiVersion: v2
type: application
name: cart
version: 0.1.1
appVersion: "2.2.0"
description: OTel Demo Cart Service - C#/.NET shopping cart service
home: https://github.com/open-telemetry/opentelemetry-demo
sources:
  - https://github.com/open-telemetry/opentelemetry-demo
keywords:
  - opentelemetry
  - demo
  - cart
  - dotnet
