apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  # Required for KRaft: controller must resolve its own address before pod is ready
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.plaintextPort }}
      targetPort: {{ .Values.service.plaintextPort }}
      name: plaintext
    - port: {{ .Values.service.controllerPort }}
      targetPort: {{ .Values.service.controllerPort }}
      name: controller
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
