apiVersion: v2
type: application
name: valkey-cart
version: 0.1.0
appVersion: "9.0.1"
description: OTel Demo Valkey Cart - Redis-compatible in-memory store for the cart service
home: https://github.com/open-telemetry/opentelemetry-demo
sources:
  - https://github.com/open-telemetry/opentelemetry-demo
keywords:
  - opentelemetry
  - demo
  - valkey
  - redis
  - cart
