apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "product-catalog.fullname" . }}
  labels:
    {{- include "product-catalog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "product-catalog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "product-catalog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "product-catalog.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: product-catalog
          image: {{ include "product-catalog.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: service
              protocol: TCP
          env:
            - name: PRODUCT_CATALOG_PORT
              value: {{ .Values.service.port | quote }}
            - name: GOMEMLIMIT
              value: {{ .Values.goMemLimit | quote }}
            - name: DB_CONNECTION_STRING
              value: "postgres://{{ .Values.dependencies.postgresql.user }}:{{ .Values.dependencies.postgresql.password }}@{{ .Values.dependencies.postgresql.host }}:{{ .Values.dependencies.postgresql.port }}/{{ .Values.dependencies.postgresql.database }}?sslmode={{ .Values.dependencies.postgresql.sslMode }}"
            - name: FLAGD_HOST
              value: {{ .Values.dependencies.flagd.host | quote }}
            - name: FLAGD_PORT
              value: {{ .Values.dependencies.flagd.port | quote }}
            - name: OTEL_SEMCONV_STABILITY_OPT_IN
              value: database
            {{- if .Values.otel.enabled }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.otel.serviceName | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.exporterEndpoint | quote }}
            - name: OTEL_LOGS_EXPORTER
              value: {{ .Values.otel.logsExporter | quote }}
            - name: OTEL_TRACES_EXPORTER
              value: {{ .Values.otel.tracesExporter | quote }}
            - name: OTEL_EXPORTER_OTLP_LOGS_PROTOCOL
              value: {{ .Values.otel.logsProtocol | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
              value: {{ .Values.otel.tracesProtocol | quote }}
            - name: OTEL_METRICS_EXPORTER
              value: {{ .Values.otel.metricsExporter | quote }}
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: {{ .Values.otel.metricsTemporalityPreference | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
