apiVersion: v1
kind: Service
metadata:
  name: {{ include "ad.fullname" . }}
  labels:
    {{- include "ad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: tcp-service
  selector:
    {{- include "ad.selectorLabels" . | nindent 4 }}
