apiVersion: v2
type: application
name: product-catalog
version: 0.1.1
appVersion: "2.2.0"
description: OTel Demo Product Catalog Service - Go-based product listing service
home: https://github.com/open-telemetry/opentelemetry-demo
sources:
  - https://github.com/open-telemetry/opentelemetry-demo
keywords:
  - opentelemetry
  - demo
  - product-catalog
  - go
