apiVersion: v2
type: application
name: frontend-proxy
version: 0.1.1
appVersion: "2.2.0"
description: OTel Demo Frontend Proxy - Envoy-based reverse proxy
home: https://github.com/open-telemetry/opentelemetry-demo
sources:
  - https://github.com/open-telemetry/opentelemetry-demo
keywords:
  - opentelemetry
  - demo
  - frontend-proxy
  - envoy
