apiVersion: v2
type: application
name: checkout
version: 0.1.1
appVersion: "2.2.0"
description: OTel Demo Checkout Service - Go order processing
home: https://github.com/open-telemetry/opentelemetry-demo
sources:
  - https://github.com/open-telemetry/opentelemetry-demo
keywords:
  - opentelemetry
  - demo
  - checkout
