apiVersion: v2
type: application
name: postgresql
version: 0.1.0
appVersion: "17.6"
description: OTel Demo PostgreSQL - Database backend for product-catalog and product-reviews
home: https://github.com/open-telemetry/opentelemetry-demo
sources:
  - https://github.com/open-telemetry/opentelemetry-demo
keywords:
  - opentelemetry
  - demo
  - postgresql
  - database
