apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "checkout.fullname" . }}
  labels:
    {{- include "checkout.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "checkout.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "checkout.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "checkout.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: checkout
          image: {{ include "checkout.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: service
              protocol: TCP
          env:
            - name: CHECKOUT_PORT
              value: {{ .Values.service.port | quote }}
            - name: CART_ADDR
              value: "{{ .Values.dependencies.cart.host }}:{{ .Values.dependencies.cart.port }}"
            - name: CURRENCY_ADDR
              value: "{{ .Values.dependencies.currency.host }}:{{ .Values.dependencies.currency.port }}"
            - name: EMAIL_ADDR
              value: "http://{{ .Values.dependencies.email.host }}:{{ .Values.dependencies.email.port }}"
            - name: PAYMENT_ADDR
              value: "{{ .Values.dependencies.payment.host }}:{{ .Values.dependencies.payment.port }}"
            - name: PRODUCT_CATALOG_ADDR
              value: "{{ .Values.dependencies.productCatalog.host }}:{{ .Values.dependencies.productCatalog.port }}"
            - name: SHIPPING_ADDR
              value: "http://{{ .Values.dependencies.shipping.host }}:{{ .Values.dependencies.shipping.port }}"
            - name: FLAGD_HOST
              value: {{ .Values.dependencies.flagd.host | quote }}
            - name: FLAGD_PORT
              value: {{ .Values.dependencies.flagd.port | quote }}
            - name: GOMEMLIMIT
              value: {{ .Values.goMemLimit | quote }}
            - name: KAFKA_ADDR
              value: "{{ .Values.dependencies.kafka.host }}:{{ .Values.dependencies.kafka.port }}"
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app.kubernetes.io/component']"
            {{- if .Values.otel.enabled }}
            - name: OTEL_COLLECTOR_NAME
              value: {{ .Values.otel.collectorName | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ include "checkout.otelEndpoint" . }}
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: {{ .Values.otel.exporterProtocol | quote }}
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: {{ .Values.otel.resourceAttributes | quote }}
            - name: OTEL_LOGS_EXPORTER
              value: {{ .Values.otel.logsExporter | quote }}
            - name: OTEL_EXPORTER_OTLP_LOGS_PROTOCOL
              value: {{ .Values.otel.logsProtocol | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
