apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cart.fullname" . }}
  labels:
    {{- include "cart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "cart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "cart.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers.waitForValkey }}
      initContainers:
        - name: wait-for-valkey-cart
          image: busybox:latest
          command:
            - sh
            - -c
            - "until nc -z -v -w30 {{ .Values.dependencies.valkeyCart.host }} {{ .Values.dependencies.valkeyCart.port }}; do echo waiting for valkey-cart; sleep 2; done;"
      {{- end }}
      containers:
        - name: cart
          image: {{ include "cart.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: service
              protocol: TCP
          env:
            - name: CART_PORT
              value: {{ .Values.service.port | quote }}
            - name: ASPNETCORE_URLS
              value: "http://*:{{ .Values.service.port }}"
            - name: VALKEY_ADDR
              value: "{{ .Values.dependencies.valkeyCart.host }}:{{ .Values.dependencies.valkeyCart.port }}"
            - name: FLAGD_HOST
              value: {{ .Values.dependencies.flagd.host | quote }}
            - name: FLAGD_PORT
              value: {{ .Values.dependencies.flagd.port | quote }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
