apiVersion: v2
type: application
name: shipping
version: 0.1.0
appVersion: "2.2.0"
description: OTel Demo Shipping Service - Rust shipping calculation
home: https://github.com/open-telemetry/opentelemetry-demo
sources:
  - https://github.com/open-telemetry/opentelemetry-demo
keywords:
  - opentelemetry
  - demo
  - shipping
